"""Add new player fields

Revision ID: ba502d310e25
Revises: 
Create Date: 2024-12-29 13:20:44.966318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba502d310e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_user_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('available_tasks', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('completed_tasks', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('estimated_travel_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remaining_travel_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_gap', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('time_gap')
        batch_op.drop_column('remaining_travel_time')
        batch_op.drop_column('estimated_travel_time')
        batch_op.drop_column('completed_tasks')
        batch_op.drop_column('available_tasks')
        batch_op.drop_column('telegram_user_id')

    # ### end Alembic commands ###
